<?php
// ACCOUNT-USED@EXAMPLE.COM
// Required by letsencrypt_drupal
$acquia_cloud_token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
$acquia_cloud_secret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
